### ISSUE TITLE
debian unix socket group should be 'libvirt'

### ISSUE THREAD

**Issue by CyBeRoni** [thias/puppet-libvirt#29]
Not 'libvirtd', as that group is not created by installing libvirt-bin.

    $ getent group|grep virt
    libvirt:x:117:
    libvirt-qemu:x:118:libvirt-qemu
    $

**Comment by thias** [comment]
Thanks for the report! This has been fixed in 6974b93102533638d10f0d4a1d8463731ad95dae.
