### ISSUE TITLE
readme.md  Libvirt Storage Pools activate

### ISSUE THREAD

**Issue by unicorn-ljw** [thias/puppet-libvirt#34]
libvirt_pool { 'mypool' :
  ensure   => present,
  type     => 'dir',
  activate => false,
  target   => '/tmp/pool-dir',
}

activate should be active.

Also in the following sentence:
"By default a pool is activated ( same as activate => true)."

according to: https://github.com/thias/puppet-libvirt/blob/master/lib/puppet/type/libvirt_pool.rb

**Comment by thias** [comment]
Thanks for the fix in #35!
