### ISSUE TITLE
rspec-system tests fail to run corectly

### ISSUE THREAD

**Issue by jaggededgedjustice** [thias/puppet-libvirt#48]
I attemted to run the current rspec-system tests by using bundler to install the dependancies in the Gemfile, but the tests fail with "undefined method `success?' for #<Hash:...>".
I did check the beaker tests in #33, which did run corectly with the ubuntu 14 node.

 Is it posible to get the tests to pass with a more specific set of gem versions, or must the rspec-system tests be replaced?

**Comment by thias** [comment]
The changes in #33 have been merged now, could you please try again?

**Comment by jaggededgedjustice** [comment]
The tests do run properly now, thanks.
